In [87]:
library(dplyr)

In [ ]:
#Both metabolic.rate - minimum and maximum are all NA values, useless
#Original metabolic rate are not standardized, require more work to understand how to standardize them.

In [145]:
file <- 'dataset.csv'
df <- read.csv(file)
relevant_features = c("phylum", "class", "order", "genus", "species", "sex", "sampleSizeValue", "body.mass", "body.mass...units", "metabolic.rate", "metabolic.rate...units", "metabolic.rate...method")

In [146]:
dataset = df[relevant_features]

In [143]:
dataset[dataset$metabolic.rate...method=="basal metabolic rate",]$class
#colnames(df)

  [1] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
  [7] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [13] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [19] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [25] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [31] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [37] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [43] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [49] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [55] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [61] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [67] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [73] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [79] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [85] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [91] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
 [97] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
[103] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
[109] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
[115] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
[121] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
[127] "Aves"     "Aves"     "Aves"     "Aves"     "Aves"     "Aves"
[133] "Aves"     "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[139] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[145] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[151] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[157] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[163] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[169] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[175] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[181] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[187] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[193] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[199] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[205] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[211] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[217] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[223] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[229] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[235] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[241] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[247] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[253] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[259] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[265] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[271] "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia" "Mammalia"
[277] "Mammalia" "Mammalia" "Mammalia"

In [147]:
dataset

     phylum     class     order    genus           species
1    Chordata   Amphibia  Anura    Hyla            Hyla versicolor
2    Chordata   Amphibia  Anura    Pseudacris      Pseudacris triseriata
3    Chordata   Amphibia  Anura    Acris           Acris crepitans
4    Chordata   Amphibia  Anura    Platymantis     Platymantis vitiensis
5    Chordata   Amphibia  Anura    Rana            Rana sylvatica
6    Chordata   Amphibia  Anura    Rana            Rana pipiens
7    Chordata   Amphibia  Anura    Rana            Rana clamitans
8    Chordata   Amphibia  Anura    Xenopus         Xenopus laevis
9    Chordata   Amphibia  Anura    Rhinophrynus    Rhinophrynus dorsalis
10   Arthropoda Arachnida Araneae  Cupiennius      Cupiennius salei
11   Arthropoda Arachnida Araneae  Nephila         Nephila clavipes
12   Arthropoda Arachnida Araneae  Ephebopus       Ephebopus sp.
13   Arthropoda Arachnida Araneae  Phidippus       Phidippus regius
14   Arthropoda Arachnida Araneae  Zygiella        Zygiella x-notata
15   Arthropoda Arachnida Araneae  Zygiella        Zygiella x-notata
16   Arthropoda Arachnida Araneae  Mysmena         Mysmena sp.
17   Arthropoda Arachnida Araneae  Mysmenopsis     Mysmenopsis tengellacompa
18   Arthropoda Arachnida Araneae  Anapisona       Anapisona simoni
19   Arthropoda Arachnida Araneae  Anapisona       Anapisona simoni
20   Arthropoda Arachnida Araneae  Faiditus        Faiditus elevatus
21   Arthropoda Arachnida Araneae  Faiditus        Faiditus elevatus
22   Arthropoda Arachnida Araneae  Faiditus        Faiditus sp.
23   Arthropoda Arachnida Araneae  Eustala         Eustala illicita
24   Arthropoda Arachnida Araneae  Leucauge        Leucauge mariana
25   Arthropoda Arachnida Araneae  Leucauge        Leucauge mariana
26   Arthropoda Arachnida Araneae  Argiope         Argiope argentata
27   Arthropoda Arachnida Araneae  Nephila         Nephila clavipes
28   Arthropoda Arachnida Araneae  Nephila         Nephila clavipes
29   Arthropoda Arachnida Araneae  Eratigena       Eratigena atrica
30   Arthropoda Arachnida Araneae  Deinopis        Deinopis spinosa
⋮    ⋮          ⋮         ⋮        ⋮               ⋮
3551 Chordata   Reptilia  Squamata Aspidites       Aspidites melanocephalus
3552 Chordata   Reptilia  Squamata Antaresia       Antaresia praelongus
3553 Chordata   Reptilia  Squamata Antaresia       Antaresia childreni
3554 Chordata   Reptilia  Squamata Liasis          Liasis fuscus
3555 Chordata   Reptilia  Squamata Liasis          Liasis olivaceus
3556 Chordata   Reptilia  Squamata Antaresia       Antaresia stimsoni
3557 Chordata   Reptilia  Squamata Morelia         Morelia spilota
3558 Chordata   Reptilia  Squamata Morelia         Morelia variegata
3559 Chordata   Reptilia  Squamata Pseudonaja      Pseudonaja nuchalis
3560 Chordata   Reptilia  Squamata Tiliqua         Tiliqua rugosa
3561 Chordata   Reptilia  Squamata Varanus         Varanus rosenbergi
3562 Chordata   Reptilia  Squamata Varanus         Varanus gouldii
3563 Chordata   Reptilia  Squamata Varanus         Varanus panoptes
3564 Chordata   Reptilia  Squamata Varanus         Varanus mertensi
3565 Chordata   Reptilia  Squamata Anniella        Anniella pulchra
3566 Chordata   Reptilia  Squamata Ophisaurus      Ophisaurus ventralis
3567 Chordata   Reptilia  Squamata Trogonophis     Trogonophis wiegmanni
3568 Chordata   Reptilia  Squamata Thamnophis      Thamnophis butleri
3569 Chordata   Reptilia  Squamata Varanus         Varanus gilleni
3570 Chordata   Reptilia  Squamata Natrix          Natrix maura
3571 Chordata   Reptilia  Squamata Natrix          Natrix natrix
3572 Chordata   Reptilia  Squamata Natrix          Natrix helvetica
3573 Chordata   Reptilia  Squamata Cnemidophorus   Cnemidophorus murinus
3574 Chordata   Reptilia  Squamata Varanus         Varanus gouldii
3575 Chordata   Reptilia  Squamata Varanus         Varanus panoptes
3576 Chordata   Reptilia  Squamata Sphaerodactylus Sphaerodactylus cinereus
3577 Chordata   Reptilia  Squamata Sphaerodactylus Sphaerodactylus notatus
3578 Chordata   Reptilia  Squamata Anolis          Anolis sagrei
3579 Chordata   Reptilia  Squamata Coleonyx        Coleonyx switaki
3580 Chordata   Reptilia  Squamata Coleonyx        Coleonyx variegatus
     sex    sampleSizeValue body.mass body.mass...units metabolic.rate
1            1              0.0131500 kg                NA
2            3              0.0001000 kg                NA
3            3              0.0003000 kg                NA
4            1              0.0003000 kg                NA
5            3              0.0003700 kg                NA
6            3              0.0011000 kg                NA
7            3              0.0036200 kg                NA
8            1              0.0323700 kg                NA
9            1              0.0165700 kg                NA
10           5                     NA                   NA
11           5                     NA                   NA
12           3                     NA                   NA
13           3                     NA                   NA
14          20              0.0000390 kg                NA
15          13              0.0000290 kg                NA
16   female  1              0.0000001 kg                NA
17   female  1              0.0000003 kg                NA
18   female  1              0.0000008 kg                NA
19   male    1              0.0000008 kg                NA
20   female  1              0.0000030 kg                NA
21   male    1              0.0000024 kg                NA
22   male    1              0.0000027 kg                NA
23   male    1              0.0000140 kg                NA
24   female  1              0.0000600 kg                NA
25   male    1              0.0000200 kg                NA
26   female  1              0.0002500 kg                NA
27   female  1              0.0020000 kg                NA
28   male    1              0.0000112 kg                NA
29          10                     NA                   NA
30   male    1                     NA                   NA
⋮    ⋮      ⋮               ⋮         ⋮                 ⋮
3551         3              1.02750   kg                0.2663167103
3552         3              0.10550   kg                0.0179251632
3553         8              0.33170   kg                0.0862114992
3554         4              1.30690   kg                0.1043500571
3555         5              3.32320   kg                0.3962741434
3556         5              0.34990   kg                0.0719140476
3557         4              1.51650   kg                0.2891499538
3558         7              2.17350   kg                0.2057125871
3559         3              0.21410   kg                0.0512147520
3560        13              0.54800   kg                0.2185792350
3561        12              1.28700   kg                0.4234972678
3562         6              1.08600   kg                0.2595628415
3563         7              0.93100   kg                0.2868852459
3564         7              0.90400   kg                0.1639344262
3565         7              0.00494   kg                0.0018168222
3566         9              0.03217   kg                0.0068271889
3567         8              0.00497   kg                0.0010795944
3568        10              0.01904   kg                0.0062514667
3569         1              0.02750   kg                0.0102147327
3570        34              0.02250   kg                0.0125000000
3571        13              0.03750   kg                0.0250000000
3572         7              0.08250   kg                0.0962500000
3573        12              0.05520   kg                0.0185058769
3574         5              0.16900   kg                0.0407520049
3575        10              2.00300   kg                0.6333084636
3576         8              0.00054   kg                0.0002519324
3577         6              0.00033   kg                0.0001555624
3578        12              0.00040   kg                0.0003907285
3579         1              0.00946   kg                0.0038891111
3580         1              0.00362   kg                0.0029362222
     metabolic.rate...units metabolic.rate...method
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
⋮    ⋮                      ⋮
3551 W                      standard metabolic rate
3552 W                      standard metabolic rate
3553 W                      standard metabolic rate
3554 W                      standard metabolic rate
3555 W                      standard metabolic rate
3556 W                      standard metabolic rate
3557 W                      standard metabolic rate
3558 W                      standard metabolic rate
3559 W                      standard metabolic rate
3560 W                      standard metabolic rate
3561 W                      standard metabolic rate
3562 W                      standard metabolic rate
3563 W                      standard metabolic rate
3564 W                      standard metabolic rate
3565 W                      standard metabolic rate
3566 W                      standard metabolic rate
3567 W                      standard metabolic rate
3568 W                      standard metabolic rate
3569 W                      standard metabolic rate
3570 W                      standard metabolic rate
3571 W                      standard metabolic rate
3572 W                      standard metabolic rate
3573 W                      resting metabolic rate
3574 W                      standard metabolic rate
3575 W                      standard metabolic rate
3576 W                      standard metabolic rate
3577 W                      standard metabolic rate
3578 W                      standard metabolic rate
3579 W                      standard metabolic rate
3580 W                      standard metabolic rate

In [148]:
data_clean <- dataset %>% 
                filter(!is.na(metabolic.rate), !is.na(body.mass))

In [168]:
#CHECK NA VALUES
sum(is.na(data_clean))
#CHECK COHERENCE UNITS
sum(data_clean$body.mass...units == "kg") == nrow(data_clean)
sum(data_clean$metabolic.rate...units == "W") == nrow(data_clean)

[1] 0

[1] TRUE

[1] TRUE

In [170]:
n_distinct(dataset$class)

[1] 10

In [171]:
data_clean

     phylum     class     order          genus
1    Arthropoda Arachnida Araneae        Marpissa
2    Arthropoda Arachnida Araneae        Phidippus
3    Arthropoda Arachnida Araneae        Sarinda
4    Arthropoda Arachnida Araneae        Zygoballus
5    Arthropoda Arachnida Trombidiformes Tetranychus
6    Arthropoda Arachnida Mesostigmata   Phytoseiulus
7    Arthropoda Arachnida Araneae        Pardosa
8    Arthropoda Arachnida Araneae        Pardosa
9    Arthropoda Arachnida Araneae        Marpissa
10   Arthropoda Arachnida Araneae        Marpissa
11   Arthropoda Arachnida Araneae        Pholcus
12   Arthropoda Arachnida Araneae        Pholcus
13   Arthropoda Arachnida Araneae        Aphonopelma
14   Arthropoda Arachnida Araneae        Aphonopelma
15   Arthropoda Arachnida Amblypygi      Damon
16   Arthropoda Arachnida Araneae        Metazygia
17   Arthropoda Arachnida Araneae        Metazygia
18   Arthropoda Arachnida Araneae        Metazygia
19   Arthropoda Arachnida Araneae        Metazygia
20   Arthropoda Arachnida Araneae        Metazygia
21   Arthropoda Arachnida Araneae        Metazygia
22   Arthropoda Arachnida Araneae        Metazygia
23   Arthropoda Arachnida Araneae        Metazygia
24   Arthropoda Arachnida Araneae        Metazygia
25   Arthropoda Arachnida Araneae        Metazygia
26   Arthropoda Arachnida Araneae        Zosis
27   Arthropoda Arachnida Araneae        Zosis
28   Arthropoda Arachnida Araneae        Zosis
29   Arthropoda Arachnida Araneae        Zosis
30   Arthropoda Arachnida Araneae        Zosis
⋮    ⋮          ⋮         ⋮              ⋮
1155 Chordata   Reptilia  Squamata       Aspidites
1156 Chordata   Reptilia  Squamata       Antaresia
1157 Chordata   Reptilia  Squamata       Antaresia
1158 Chordata   Reptilia  Squamata       Liasis
1159 Chordata   Reptilia  Squamata       Liasis
1160 Chordata   Reptilia  Squamata       Antaresia
1161 Chordata   Reptilia  Squamata       Morelia
1162 Chordata   Reptilia  Squamata       Morelia
1163 Chordata   Reptilia  Squamata       Pseudonaja
1164 Chordata   Reptilia  Squamata       Tiliqua
1165 Chordata   Reptilia  Squamata       Varanus
1166 Chordata   Reptilia  Squamata       Varanus
1167 Chordata   Reptilia  Squamata       Varanus
1168 Chordata   Reptilia  Squamata       Varanus
1169 Chordata   Reptilia  Squamata       Anniella
1170 Chordata   Reptilia  Squamata       Ophisaurus
1171 Chordata   Reptilia  Squamata       Trogonophis
1172 Chordata   Reptilia  Squamata       Thamnophis
1173 Chordata   Reptilia  Squamata       Varanus
1174 Chordata   Reptilia  Squamata       Natrix
1175 Chordata   Reptilia  Squamata       Natrix
1176 Chordata   Reptilia  Squamata       Natrix
1177 Chordata   Reptilia  Squamata       Cnemidophorus
1178 Chordata   Reptilia  Squamata       Varanus
1179 Chordata   Reptilia  Squamata       Varanus
1180 Chordata   Reptilia  Squamata       Sphaerodactylus
1181 Chordata   Reptilia  Squamata       Sphaerodactylus
1182 Chordata   Reptilia  Squamata       Anolis
1183 Chordata   Reptilia  Squamata       Coleonyx
1184 Chordata   Reptilia  Squamata       Coleonyx
     species                  sex    sampleSizeValue body.mass
1    Marpissa bina                    3              1.680e-04
2    Phidippus clarus                 7              2.600e-04
3    Sarinda hentzi                   2              4.600e-06
4    Zygoballus rufipes               2              3.000e-06
5    Tetranychus cinnabarinus male    5              4.940e-09
6    Phytoseiulus persimilis  male   12              8.590e-09
7    Pardosa lugubris         female 24              2.240e-05
8    Pardosa lugubris         male   25              2.140e-05
9    Marpissa muscosa         female 20              3.910e-05
10   Marpissa muscosa         male   20              2.750e-05
11   Pholcus phalangioideus   female 27              2.760e-05
12   Pholcus phalangioideus   male   12              1.130e-05
13   Aphonopelma anax         female 10              1.319e-02
14   Aphonopelma anax         male   38              7.780e-03
15   Damon annulatipes                1              6.400e-04
16   Metazygia rogenhoferi            1              1.440e-05
17   Metazygia rogenhoferi            1              2.350e-05
18   Metazygia rogenhoferi            1              1.600e-05
19   Metazygia rogenhoferi            1              1.530e-05
20   Metazygia rogenhoferi            1              2.450e-05
21   Metazygia rogenhoferi            1              1.720e-05
22   Metazygia rogenhoferi            1              1.400e-05
23   Metazygia rogenhoferi            1              2.040e-05
24   Metazygia rogenhoferi            1              1.550e-05
25   Metazygia rogenhoferi            1              1.790e-05
26   Zosis geniculata                 1              3.430e-05
27   Zosis geniculata                 1              3.010e-05
28   Zosis geniculata                 1              2.480e-05
29   Zosis geniculata                 1              2.860e-05
30   Zosis geniculata                 1              5.110e-05
⋮    ⋮                        ⋮      ⋮               ⋮
1155 Aspidites melanocephalus         3              1.02750
1156 Antaresia praelongus             3              0.10550
1157 Antaresia childreni              8              0.33170
1158 Liasis fuscus                    4              1.30690
1159 Liasis olivaceus                 5              3.32320
1160 Antaresia stimsoni               5              0.34990
1161 Morelia spilota                  4              1.51650
1162 Morelia variegata                7              2.17350
1163 Pseudonaja nuchalis              3              0.21410
1164 Tiliqua rugosa                  13              0.54800
1165 Varanus rosenbergi              12              1.28700
1166 Varanus gouldii                  6              1.08600
1167 Varanus panoptes                 7              0.93100
1168 Varanus mertensi                 7              0.90400
1169 Anniella pulchra                 7              0.00494
1170 Ophisaurus ventralis             9              0.03217
1171 Trogonophis wiegmanni            8              0.00497
1172 Thamnophis butleri              10              0.01904
1173 Varanus gilleni                  1              0.02750
1174 Natrix maura                    34              0.02250
1175 Natrix natrix                   13              0.03750
1176 Natrix helvetica                 7              0.08250
1177 Cnemidophorus murinus           12              0.05520
1178 Varanus gouldii                  5              0.16900
1179 Varanus panoptes                10              2.00300
1180 Sphaerodactylus cinereus         8              0.00054
1181 Sphaerodactylus notatus          6              0.00033
1182 Anolis sagrei                   12              0.00040
1183 Coleonyx switaki                 1              0.00946
1184 Coleonyx variegatus              1              0.00362
     body.mass...units metabolic.rate metabolic.rate...units
1    kg                2.042753e-04   W
2    kg                3.614101e-04   W
3    kg                1.571348e-05   W
4    kg                4.714045e-06   W
5    kg                2.607222e-08   W
6    kg                9.878500e-08   W
7    kg                3.566259e-05   W
8    kg                3.253060e-05   W
9    kg                4.958925e-05   W
10   kg                3.586678e-05   W
11   kg                3.674197e-05   W
12   kg                1.748230e-05   W
13   kg                9.661836e-04   W
14   kg                1.268116e-03   W
15   kg                3.076816e-04   W
16   kg                5.000000e-05   W
17   kg                1.044444e-04   W
18   kg                6.166667e-05   W
19   kg                4.888889e-05   W
20   kg                6.333333e-05   W
21   kg                5.888889e-05   W
22   kg                5.888889e-05   W
23   kg                7.777778e-05   W
24   kg                4.777778e-05   W
25   kg                6.388889e-05   W
26   kg                6.055556e-05   W
27   kg                4.055556e-05   W
28   kg                4.777778e-05   W
29   kg                5.111111e-05   W
30   kg                1.183333e-04   W
⋮    ⋮                 ⋮              ⋮
1155 kg                0.2663167103   W
1156 kg                0.0179251632   W
1157 kg                0.0862114992   W
1158 kg                0.1043500571   W
1159 kg                0.3962741434   W
1160 kg                0.0719140476   W
1161 kg                0.2891499538   W
1162 kg                0.2057125871   W
1163 kg                0.0512147520   W
1164 kg                0.2185792350   W
1165 kg                0.4234972678   W
1166 kg                0.2595628415   W
1167 kg                0.2868852459   W
1168 kg                0.1639344262   W
1169 kg                0.0018168222   W
1170 kg                0.0068271889   W
1171 kg                0.0010795944   W
1172 kg                0.0062514667   W
1173 kg                0.0102147327   W
1174 kg                0.0125000000   W
1175 kg                0.0250000000   W
1176 kg                0.0962500000   W
1177 kg                0.0185058769   W
1178 kg                0.0407520049   W
1179 kg                0.6333084636   W
1180 kg                0.0002519324   W
1181 kg                0.0001555624   W
1182 kg                0.0003907285   W
1183 kg                0.0038891111   W
1184 kg                0.0029362222   W
     metabolic.rate...method
1    not specified
2    not specified
3    not specified
4    not specified
5    not specified
6    not specified
7    not specified
8    not specified
9    not specified
10   not specified
11   not specified
12   not specified
13   not specified
14   not specified
15   standard metabolic rate
16   not specified
17   not specified
18   not specified
19   not specified
20   not specified
21   not specified
22   not specified
23   not specified
24   not specified
25   not specified
26   not specified
27   not specified
28   not specified
29   not specified
30   not specified
⋮    ⋮
1155 standard metabolic rate
1156 standard metabolic rate
1157 standard metabolic rate
1158 standard metabolic rate
1159 standard metabolic rate
1160 standard metabolic rate
1161 standard metabolic rate
1162 standard metabolic rate
1163 standard metabolic rate
1164 standard metabolic rate
1165 standard metabolic rate
1166 standard metabolic rate
1167 standard metabolic rate
1168 standard metabolic rate
1169 standard metabolic rate
1170 standard metabolic rate
1171 standard metabolic rate
1172 standard metabolic rate
1173 standard metabolic rate
1174 standard metabolic rate
1175 standard metabolic rate
1176 standard metabolic rate
1177 resting metabolic rate
1178 standard metabolic rate
1179 standard metabolic rate
1180 standard metabolic rate
1181 standard metabolic rate
1182 standard metabolic rate
1183 standard metabolic rate
1184 standard metabolic rate